In [13]:
import datetime
import polars as pl
import numpy as np
from utils import find_contract_expiry

In [14]:
etf_returns = pl.read_excel("./etf returns.xlsx")
# display(etf_returns.head(2))

cboe_vx = pl.read_excel("./cboe vx.xlsx")
# display(cboe_vx.head(2))

In [15]:
left = etf_returns.select([pl.col("column_0").alias("date"), "BATS:VIXY - Return"])
right = etf_returns.select(["_1", "ARCX:SPY - Return"])
etf_returns = left.join(right, left_on="date", right_on="_1", how="inner")
etf_returns = etf_returns.sort(by="date")
etf_returns = etf_returns.rename({"date": "Trade Date"})

print(f"vx zero close prices: {cboe_vx.select(pl.col('Close') == 0).sum().item()}")
# cloes prices are actually handled differently in futures markets. if there are no trades in the last minutes of the trading day, the exchange will mark the close as 0.
# lets just use the settle price, which is apparently the preferred price metric used in futures markets
cboe_vx = cboe_vx.select([
    pl.col("Trade Date"), 
    pl.col("Futures").alias("Contract Date"), 
    pl.col("Futures")
        .str.extract(r"\((.*)\)", 1) # fuck regex
        .str.to_date(format="%b %Y")
        .map_elements(find_contract_expiry, return_dtype=pl.Date)
        .alias("Contract Expiry"), 
    pl.col("Settle")
])
cboe_vx = cboe_vx.with_columns((pl.col("Contract Expiry") - pl.col("Trade Date")).dt.total_days().alias("Days to Expiry"))

cboe_vx = cboe_vx.sort(by="Trade Date")

display(etf_returns.head(2))
display(cboe_vx.head(2))

vx zero close prices: 75

shape: (2, 3)
┌────────────┬────────────────────┬───────────────────┐
│ Trade Date ┆ BATS:VIXY - Return ┆ ARCX:SPY - Return │
│ ---        ┆ ---                ┆ ---               │
│ date       ┆ f64                ┆ f64               │
╞════════════╪════════════════════╪═══════════════════╡
│ 2023-03-17 ┆ 10.5315            ┆ -1.16478          │
│ 2023-03-20 ┆ -4.18522           ┆ 0.96156           │
└────────────┴────────────────────┴───────────────────┘

shape: (2, 5)
┌────────────┬───────────────┬─────────────────┬────────┬────────────────┐
│ Trade Date ┆ Contract Date ┆ Contract Expiry ┆ Settle ┆ Days to Expiry │
│ ---        ┆ ---           ┆ ---             ┆ ---    ┆ ---            │
│ date       ┆ str           ┆ date            ┆ f64    ┆ i64            │
╞════════════╪═══════════════╪═════════════════╪════════╪════════════════╡
│ 2024-04-22 ┆ F (Jan 2025)  ┆ 2025-01-22      ┆ 19.25  ┆ 275            │
│ 2024-04-23 ┆ F (Jan 2025)  ┆ 2025-01-22      ┆ 18.7   ┆ 274            │
└────────────┴───────────────┴─────────────────┴────────┴────────────────┘

In [16]:
dates = cboe_vx.select(pl.col("Trade Date")).unique()

from utils import interp_targets
curve_table = cboe_vx.group_by("Trade Date").map_groups(interp_targets).sort("Trade Date").drop_nulls()
curve_table = curve_table.with_columns([(pl.col("t_7") / pl.col("t_30")).alias("7/30 ratio"), (pl.col("t_30") / pl.col("t_60")).alias("30/60 ratio"), (pl.col("t_30") / pl.col("t_90")).alias("30/90 ratio"), (pl.col("t_30") / pl.col("t_120")).alias("30/120 ratio")])
curve_table = curve_table.with_columns([(pl.col("t_7") > pl.col("t_30")).alias("7/30 flag"), (pl.col("t_30") > pl.col("t_60")).alias("30/60 flag"), (pl.col("t_30") > pl.col("t_90")).alias("30/90 flag"), (pl.col("t_30") > pl.col("t_120")).alias("30/120 flag")])
curve_table

shape: (451, 14)
┌─────────────┬─────────────┬─────────────┬─────────────┬───┬───────┬───────┬─────────────┬────────┐
│ Trade Date  ┆ t_7         ┆ t_30        ┆ t_60        ┆ … ┆ 7/30  ┆ 30/60 ┆ 30/90 flag  ┆ 30/120 │
│ ---         ┆ ---         ┆ ---         ┆ ---         ┆   ┆ flag  ┆ flag  ┆ ---         ┆ flag   │
│ date        ┆ f64         ┆ f64         ┆ f64         ┆   ┆ ---   ┆ ---   ┆ bool        ┆ ---    │
│             ┆             ┆             ┆             ┆   ┆ bool  ┆ bool  ┆             ┆ bool   │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══╪═══════╪═══════╪═════════════╪════════╡
│ 2024-05-28  ┆ 14.725      ┆ 15.0125     ┆ 15.3875     ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-29  ┆ 14.26875    ┆ 14.617857   ┆ 15.073214   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-30  ┆ 14.594643   ┆ 14.902679   ┆ 15.304464   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-31  ┆ 13.844643   ┆ 14.214286   ┆ 14.696429   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-06-03  ┆ 14.296429   ┆ 14.625      ┆ 15.053571   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ …           ┆ …           ┆ …           ┆ …           ┆ … ┆ …     ┆ …     ┆ …           ┆ …      │
│ 2026-03-09  ┆ 23.608457   ┆ 23.5673     ┆ 22.517793   ┆ … ┆ true  ┆ true  ┆ true        ┆ true   │
│ 2026-03-10  ┆ 25.137354   ┆ 25.0953     ┆ 22.908514   ┆ … ┆ true  ┆ true  ┆ true        ┆ true   │
│ 2026-03-11  ┆ 23.5823     ┆ 23.5823     ┆ 22.381282   ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
│ 2026-03-12  ┆ 25.8135     ┆ 25.8135     ┆ 23.0271     ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
│ 2026-03-13  ┆ 26.3706     ┆ 26.3706     ┆ 23.284707   ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
└─────────────┴─────────────┴─────────────┴─────────────┴───┴───────┴───────┴─────────────┴────────┘

In [17]:
main = etf_returns.join(curve_table, on="Trade Date")
main

shape: (450, 16)
┌─────────────┬─────────────┬─────────────┬─────────────┬───┬───────┬───────┬─────────────┬────────┐
│ Trade Date  ┆ BATS:VIXY - ┆ ARCX:SPY -  ┆ t_7         ┆ … ┆ 7/30  ┆ 30/60 ┆ 30/90 flag  ┆ 30/120 │
│ ---         ┆ Return      ┆ Return      ┆ ---         ┆   ┆ flag  ┆ flag  ┆ ---         ┆ flag   │
│ date        ┆ ---         ┆ ---         ┆ f64         ┆   ┆ ---   ┆ ---   ┆ bool        ┆ ---    │
│             ┆ f64         ┆ f64         ┆             ┆   ┆ bool  ┆ bool  ┆             ┆ bool   │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══╪═══════╪═══════╪═════════════╪════════╡
│ 2024-05-28  ┆ 2.51346     ┆ 0.06989     ┆ 14.725      ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-29  ┆ 3.67776     ┆ -0.70025    ┆ 14.26875    ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-30  ┆ -0.16892    ┆ -0.66337    ┆ 14.594643   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-05-31  ┆ -3.21489    ┆ 0.91081     ┆ 13.844643   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ 2024-06-03  ┆ -0.52448    ┆ 0.08154     ┆ 14.296429   ┆ … ┆ false ┆ false ┆ false       ┆ false  │
│ …           ┆ …           ┆ …           ┆ …           ┆ … ┆ …     ┆ …     ┆ …           ┆ …      │
│ 2026-03-09  ┆ -9.52104    ┆ 0.87599     ┆ 23.608457   ┆ … ┆ true  ┆ true  ┆ true        ┆ true   │
│ 2026-03-10  ┆ 4.8444      ┆ -0.1607     ┆ 25.137354   ┆ … ┆ true  ┆ true  ┆ true        ┆ true   │
│ 2026-03-11  ┆ -4.55936    ┆ -0.12552    ┆ 23.5823     ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
│ 2026-03-12  ┆ 6.82911     ┆ -1.51849    ┆ 25.8135     ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
│ 2026-03-13  ┆ 1.68067     ┆ -0.56602    ┆ 26.3706     ┆ … ┆ false ┆ true  ┆ true        ┆ true   │
└─────────────┴─────────────┴─────────────┴─────────────┴───┴───────┴───────┴─────────────┴────────┘

In [18]:
from utils import add_cumret
short = main
main = add_cumret(main, "7/30 ratio", "BATS:VIXY - Return")
main = add_cumret(main, "30/60 ratio", "BATS:VIXY - Return")
main = add_cumret(main, "30/90 ratio", "BATS:VIXY - Return")
main = add_cumret(main, "30/120 ratio", "BATS:VIXY - Return")
main

shape: (450, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Trade     ┆ BATS:VIXY ┆ ARCX:SPY  ┆ t_7       ┆ … ┆ return    ┆ cumret:   ┆ return    ┆ cumret:  │
│ Date      ┆ - Return  ┆ - Return  ┆ ---       ┆   ┆ earned:   ┆ 30/90     ┆ earned:   ┆ 30/120   │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ 30/90     ┆ ratio     ┆ 30/120    ┆ ratio    │
│ date      ┆ f64       ┆ f64       ┆           ┆   ┆ ratio     ┆ ---       ┆ ratio (s… ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ (sh…      ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆ f64       ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-05-2 ┆ 2.51346   ┆ 0.06989   ┆ 14.725    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3.67776   ┆ -0.70025  ┆ 14.26875  ┆ … ┆ 3.502767  ┆ 1.035028  ┆ 3.421371  ┆ 1.034214 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-3 ┆ -0.16892  ┆ -0.66337  ┆ 14.594643 ┆ … ┆ -0.159013 ┆ 1.033382  ┆ -0.154483 ┆ 1.032616 │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-3 ┆ -3.21489  ┆ 0.91081   ┆ 13.844643 ┆ … ┆ -3.050408 ┆ 1.001859  ┆ -2.974321 ┆ 1.001903 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-0 ┆ -0.52448  ┆ 0.08154   ┆ 14.296429 ┆ … ┆ -0.49116  ┆ 0.996939  ┆ -0.476039 ┆ 0.997133 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2026-03-0 ┆ -9.52104  ┆ 0.87599   ┆ 23.608457 ┆ … ┆ -11.94294 ┆ 0.520404  ┆ -13.23810 ┆ 0.369179 │
│ 9         ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 5         ┆          │
│ 2026-03-1 ┆ 4.8444    ┆ -0.1607   ┆ 25.137354 ┆ … ┆ 5.213112  ┆ 0.547534  ┆ 5.364329  ┆ 0.388982 │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-1 ┆ -4.55936  ┆ -0.12552  ┆ 23.5823   ┆ … ┆ -5.285675 ┆ 0.518593  ┆ -5.612795 ┆ 0.36715  │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-1 ┆ 6.82911   ┆ -1.51849  ┆ 25.8135   ┆ … ┆ 7.420981  ┆ 0.557077  ┆ 7.660969  ┆ 0.395277 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-1 ┆ 1.68067   ┆ -0.56602  ┆ 26.3706   ┆ … ┆ 2.019823  ┆ 0.568329  ┆ 2.176697  ┆ 0.403881 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
short = short.with_columns((~pl.col("30/60 flag")).alias("inverse 30/60 flag"))
short = add_cumret(short, "inverse 30/60 flag", "BATS:VIXY - Return")

In [ ]:
# check to see if the greater the ratio of front month : back month, the higher the return on VIXY